### ISSUE TITLE
Style the main google image in the GoogleImageSearch.html page

### ISSUE THREAD

**Issue by sunami09** [Multiprocessing-Muggles/Google-Clone#7]
<b>Use HTML and CSS only. Don't change any class name or id names of existing tags.</b>
## From this:
![image](https://user-images.githubusercontent.com/66564001/173393331-91556e31-168d-48f2-b169-6a0cf5246a32.png)

## To This:
![image](https://user-images.githubusercontent.com/66564001/173393401-e3dc66bf-7c61-4822-afe2-d99f5f94c15c.png)

**Comment by MisansProducts** [comment]
Hi! I first want to mention that it is kind of weird how `GoogleImageSearch.css` is not used in its HTML file, but I didn't question it and edited the `index.css` instead.

In order to get the "Images" text to be on top of the Google logo, the magic is in using `position: absolute` to allow overlaying elements.

As for specific things such as the color of the text, you can get those by using inspect element on the actual Google Images page that you want to copy from.

I gave the "google-image" div a `position: relative` so that elements inside of that div position themselves relative to it. Finally, I used pixel perfect measurements to get the "Images" subtext exactly where you wanted it.

I added a pull request. Let me know if it works.

**Comment by sunami09** [comment]
Hey, @MisansProducts would like to join our organization?

**Comment by sunami09** [comment]
Solved by @MisansProducts Thank You for the contribution. 😀😀

**Comment by MisansProducts** [comment]
> Hey, @MisansProducts would like to join our organization?

Sure, if that means I can help wherever I can.

**Comment by sunami09** [comment]
@MisansProducts Check your email I have sent you invitation.
